import { chromium } from "@playwright/test";
import { ensureBrowser, getVideoMetadata } from "@remotion/renderer";
import { mkdir, writeFile, readdir } from "node:fs/promises";
import { resolve, join } from "node:path";
import { tmpdir } from "node:os";
import assert from "node:assert/strict";

const output = resolve("test-results/browser");
await mkdir(output, { recursive: true });
const browserInfo = await ensureBrowser();
assert.ok("path" in browserInfo);
const browser = await chromium.launch({ executablePath: browserInfo.path, args: ["--use-fake-device-for-media-stream", "--use-fake-ui-for-media-stream", "--autoplay-policy=no-user-gesture-required"] });
const page = await browser.newPage({ viewport: { width: 1280, height: 1000 } });
page.setDefaultTimeout(20000);
const errors = [];
page.on("pageerror", (error) => { errors.push(error.message); console.error(error.message); });
try {
  await page.goto("http://127.0.0.1:3000");
  let uploads = 0;
  page.on("request", (req) => { if (req.url().endsWith("/api/render")) uploads++; });
  const before = (await readdir(tmpdir())).filter((name) => name.startsWith("hand-dance-"));
  const responsePromise = page.waitForResponse((response) => response.url().endsWith("/api/render"), { timeout: 200000 });
  await page.getByRole("link", { name: /Test Now/ }).click();
  await page.waitForURL("**/record");
  await page.locator(".motion-overlay").waitFor();
  await page.getByRole("button", { name: "Ready to record?" }).click();
  await page.waitForURL("**/results", { timeout: 25000 });
  console.log("Ready button completed both camera recordings and started rendering automatically.");
  const result = await responsePromise;
  if (!result.ok()) throw new Error(`Render failed (${result.status()}): ${await result.text()}`);
  const download = page.getByRole("link", { name: /Download MP4/ });
  await download.waitFor();
  const path = join(output, "dance.mp4");
  await writeFile(path, await result.body());
  const metadata = await getVideoMetadata(path);
  assert.equal(metadata.codec, "h264"); assert.equal(metadata.audioCodec, "aac");
  assert.equal(metadata.width, 960); assert.equal(metadata.height, 540);
  assert.ok(Math.abs(metadata.durationInSeconds - 11) < .1);
  await page.getByLabel("Your final dance video").evaluate(async (video) => { video.muted = true; await video.play(); });
  await page.waitForFunction(() => document.querySelector('.reveal video').currentTime > .2);
  await page.screenshot({ path: join(output, "reveal.png"), fullPage: true });
  await page.getByRole("button", { name: "Delete recording and return home", exact: true }).click();
  assert.equal(await page.locator(".clip-grid video, .reveal video").count(), 0);
  const after = (await readdir(tmpdir())).filter((name) => name.startsWith("hand-dance-"));
  assert.deepEqual(after, before);
  assert.equal(uploads, 1);
  assert.deepEqual(errors, []);
  console.log("PASS: ready-button flow, two real recordings, eleven-second H.264/AAC MP4, playback, deletion and temporary-file cleanup.");
} catch (error) {
  await page.screenshot({ path: join(output, "failure.png"), fullPage: true }).catch(() => {});
  throw error;
} finally { await browser.close(); }
